project:
  type: default
  execute-dir: project # the working directory for computations
  output-dir: _outputs
  
author: 
  - name: Maël Delem
    orcid: 0009-0005-8518-1991
    email: mael.delem@univ-lyon2.fr
    corresponding: true
    url: https://emc.univ-lyon2.fr/equipes/memoire-emotion-et-attention-mea/delem-mael
    affiliations:
    - id: emc
      name: Study of Cognitive Mechanisms (EMC) Laboratory, Université Lumière Lyon 2
      city: Lyon
      country: France
      url: https://emc.univ-lyon2.fr

date-modified: last-modified

bibliography:
  - "bibliography/references.bib" 
csl: "bibliography/apa.csl"

execute:
  freeze: false
  warning: false
  error: false
  message: false

# crossref:
#   chapters: true # for figures numbered by chapter

format:
  html:
    embed-resources: true
    theme: 
      dark:
        - scss/custom-theme.scss
        - scss/default-vars.scss
        - scss/colours-dark.scss
      light:
        - scss/custom-theme.scss
        - scss/default-vars.scss
        - scss/colours-light.scss
    highlight-style: github
    lightbox: true          
    code-fold: true         
    code-tools: true        
    code-annotations: hover 
    title-block-banner: true
    toc: true
    toc-location: right
    toc-depth: 2
    toc-expand: 1
    number-sections: true
    number-depth: 2
    filters:
      - add-code-files